/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>
#include "tcMenuTfteSpi.h"
#include <graphics/MenuTouchScreenEncoder.h>
#include "tcMenuAdaTouchDriver.h"
#include <RemoteMenuItem.h>
#include <RuntimeMenuItem.h>
#include <ScrollChoiceMenuItem.h>
#include <EditableLargeNumberMenuItem.h>
#include <IoAbstraction.h>
#include <ArduinoEEPROMAbstraction.h>
#include <RemoteAuthentication.h>

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern TFT_eSPI gfx;
extern TfteSpiDrawable gfxDrawable;
extern GraphicsDeviceRenderer renderer;
extern XPT2046_Touchscreen touchDevice;
extern iotouch::AdaLibTouchInterrogator touchInterrogator;
extern MenuTouchScreenManager touchScreen;

// Any externals needed by IO expanders, EEPROMs etc


// Global Menu Item exports
extern EepromAuthenticationInfoMenuItem menuConnectivityAuthenticator;
extern RemoteMenuItem menuConnectivityIoTMonitor;
extern BackMenuItem menuBackConnectivity;
extern SubMenuItem menuConnectivity;
extern ListRuntimeMenuItem menuMoreItemsMyList;
extern Rgb32MenuItem menuMoreItemsRGB;
extern TimeFormattedMenuItem menuMoreItemsNewTextItem;
extern DateFormattedMenuItem menuMoreItemsDate;
extern ActionMenuItem menuMoreItemsPressMe;
extern BooleanMenuItem menuMoreItemsBool1;
extern BackMenuItem menuBackMoreItems;
extern SubMenuItem menuMoreItems;
extern EnumMenuItem menuFoods;
extern EditableLargeNumberMenuItem menuLargeNum;
extern AnalogMenuItem menuHalves;
extern AnalogMenuItem menuDecimalTens;

// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return menuDecimalTens; }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

int fnMoreItemsMyListRtCall(RuntimeMenuItem* item, uint8_t row, RenderFnMode mode, char* buffer, int bufferSize);
void CALLBACK_FUNCTION onDecimalTens(int id);
void CALLBACK_FUNCTION onLargeNum(int id);
void CALLBACK_FUNCTION onPressMe(int id);

#endif // MENU_GENERATED_CODE_H
