/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

// Generated for PicoSDK/STMCube CMake by TcMenu 5.0.0-SNAPSHOT on 2026-09-05T16:10:34.519750Z.

#include <tcMenu.h>
#include "PicoSDKOled_menu.h"

// Each plugin's code now follows here

// PLUGIN FILE - tcMenuAdaFruitGfxMono.cpp
/*
 * Copyright (c) 2018 https://www.thecoderscorner.com (Dave Cherry).
 * This product is licensed under an Apache license, see the LICENSE file in the top-level directory.
 */

/**
 * Adafruit_GFX renderer that renders menus onto this type of display. This file is a plugin file and should not
 * be directly edited, it will be replaced each time the project is built. If you want to edit this file in place,
 * make sure to rename it first.
 * 
 * LIBRARY REQUIREMENT
 * This library requires the AdaGfx library along with a suitable driver.
 */

#include <ScrollChoiceMenuItem.h>

#include <tcUnicodeHelper.h>
#include <tcUnicodeAdaGFX.h>

using namespace tcgfx;

void AdafruitDrawable::transaction(bool isStarting, bool redrawNeeded) {
    if(!isStarting && redrawNeeded) {
        reinterpret_cast<AdafruitSSD1306Spi*>(graphics)->display();
    }
}

void AdafruitDrawable::internalDrawText(const Coord &where, const void *font, int mag, const char *sz) {
    int baseline=0;
    Coord exts = textExtents(font, mag, "(;y", &baseline);
    int yCursor = font ? (where.y + (exts.y - baseline)) : where.y;
    graphics->setCursor(where.x, yCursor);
    graphics->setTextColor(drawColor);
    graphics->print(sz);
}

void AdafruitDrawable::drawBitmap(const Coord &where, const DrawableIcon *icon, bool selected) {
    if(icon->getIconType() == DrawableIcon::ICON_XBITMAP) {
        graphics->fillRect(where.x, where.y, icon->getDimensions().x, icon->getDimensions().y, backgroundColor);
        graphics->drawXBitmap(where.x, where.y, icon->getIcon(selected), icon->getDimensions().x, icon->getDimensions().y, drawColor);
    }
    else if(icon->getIconType() == DrawableIcon::ICON_NATIVE) {
        graphics->drawRGBBitmap(where.x, where.y, (const uint16_t*)icon->getIcon(selected), icon->getDimensions().x, icon->getDimensions().y);
    }
    else if(icon->getIconType() == DrawableIcon::ICON_MONO) {
        graphics->drawBitmap(where.x, where.y, icon->getIcon(selected), icon->getDimensions().x, icon->getDimensions().y, drawColor, backgroundColor);
    }
}

void AdafruitDrawable::drawXBitmap(const Coord &where, const Coord &size, const uint8_t *data) {
    graphics->fillRect(where.x, where.y, size.x, size.y, backgroundColor);
    graphics->drawXBitmap(where.x, where.y, data, size.x, size.y, drawColor);
}

void AdafruitDrawable::drawBox(const Coord &where, const Coord &size, bool filled) {
    if(filled) {
        graphics->fillRect(where.x, where.y, size.x, size.y, drawColor);
    }
    else {
        graphics->drawRect(where.x, where.y, size.x, size.y, drawColor);
    }
}

void AdafruitDrawable::drawCircle(const Coord& where, int radius, bool filled) {
    if(filled) {
        graphics->fillCircle(where.x, where.y, radius, drawColor);
    }
    else {
        graphics->drawCircle(where.x, where.y, radius, drawColor);
    }
}

void AdafruitDrawable::drawPolygon(const Coord points[], int numPoints, bool filled) {
    if(numPoints == 2) {
        graphics->drawLine(points[0].x, points[0].y, points[1].x, points[1].y, drawColor);
    }
    else if(numPoints == 3) {
        if(filled) {
            graphics->fillTriangle(points[0].x, points[0].y, points[1].x, points[1].y, points[2].x, points[2].y, drawColor);
        }
        else {
            graphics->drawTriangle(points[0].x, points[0].y, points[1].x, points[1].y, points[2].x, points[2].y, drawColor);
        }
    }
}

Coord AdafruitDrawable::internalTextExtents(const void *f, int mag, const char *text, int *baseline) {
    if(mag == 0) mag = 1; // never allow 0 magnification

    graphics->setFont(static_cast<const GFXfont *>(f));
    graphics->setTextSize(mag);
    auto* font = (GFXfont *) f;
    int16_t x1, y1;
    uint16_t w, h;
    graphics->getTextBounds((char*)text, 3, font?30:2, &x1, &y1, &w, &h);

    if(font == nullptr) {
        // for the default font, the starting offset is 0, and we calculate the height.
        if(baseline) *baseline = 0;
        return Coord(w, h);
    }
    else {
        computeBaselineIfNeeded(font);
        if(baseline) *baseline = (computedBaseline * mag);
        return Coord(int(w), (computedHeight * mag));
    }
}

void AdafruitDrawable::computeBaselineIfNeeded(const GFXfont* font) {
    // we cache the last baseline, if the font is unchanged, don't calculate again
    if(computedFont == font && computedBaseline > 0) return;

    // we need to work out the biggest glyph and maximum extent beyond the baseline, we use 4 chars 'Agj(' for this
    const char sz[] = "Agj(";
    int height = 0;
    int bl = 0;
    const char* current = sz;
    auto fontLast = pgm_read_word(&font->last);
    auto fontFirst = pgm_read_word(&font->first);
    while(*current && (*current < fontLast)) {
        size_t glIdx = *current - fontFirst;
        auto allGlyphs = (GFXglyph*)pgm_read_ptr(&font->glyph);
        int glyphHeight = int(pgm_read_byte(&allGlyphs[glIdx].height));
        if (glyphHeight > height) height = glyphHeight;
        auto yOffset = int8_t(pgm_read_byte(&allGlyphs[glIdx].yOffset));
        bl += glyphHeight + yOffset;
        current++;
    }
    computedFont = font;
    computedBaseline = bl / 4;
    computedHeight = height;
}

void AdafruitDrawable::drawPixel(uint16_t x, uint16_t y) {
    graphics->writePixel(x, y, drawColor);
}

UnicodeFontHandler *AdafruitDrawable::createFontHandler() {
    return new UnicodeFontHandler(newAdafruitTextPipeline(graphics), ENCMODE_UTF8);
}

//
// helper functions
//

void drawCookieCutBitmap(Adafruit_GFX* gfx, int16_t x, int16_t y, const uint8_t *bitmap, int16_t w,
                         int16_t h, int16_t totalWidth, int16_t xStart, int16_t yStart,
                         uint16_t fgColor, uint16_t bgColor) {

    // total width here is different to the width we are drawing, imagine rolling out a long
    // line of dough and cutting cookies from it. The cookie is the part of the image we want
    uint16_t byteWidth = (totalWidth + 7) / 8; // Bitmap scanline pad = whole byte
    uint16_t yEnd = h + yStart;
    uint16_t xEnd = w + xStart;
    uint8_t byte;

    gfx->startWrite();

    for (uint16_t j = yStart; j < yEnd; j++, y++) {
        byte = bitmap[size_t(((j * byteWidth) + xStart) / 8)];
        for (uint16_t i = xStart; i < xEnd; i++) {
            if (i & 7U)
                byte <<= 1U;
            else
                byte = bitmap[size_t((j * byteWidth) + i / 8)];
            gfx->writePixel(x + (i - xStart), y, (byte & 0x80U) ? fgColor : bgColor);
        }
    }

    gfx->endWrite();
}


// PLUGIN FILE - StdioTransport.cpp



int StdioTransport::writeStr(const char *data) {
    auto dl = strlen(data);
    for(size_t i = 0; i<dl; ++i) {
        putchar_raw(data[i]);
    }
    return (int)dl;
}

uint8_t StdioTransport::readByte() {
    if (inputBuffer.available()) {
        return inputBuffer.get();
    }
    return -1;
}

void StdioTransport::close() {
    currentField.msgType = UNKNOWN_MSG_TYPE;
    currentField.fieldType = FVAL_PROCESSING_AWAITINGMSG;
}

int StdioTransport::writeChar(char data) {
    putchar_raw(data);
    return 1;
}


bool StdioTransport::readAvailable() {
    int ch;
    while ((ch=getchar_timeout_us(0)) != PICO_ERROR_TIMEOUT) {
        inputBuffer.put(ch);
    }
    return inputBuffer.available();
}

#include <Fonts/OpenSansRegular7pt.h>
#include <Fonts/OpenSansRegular8pt.h>
#include "ThemeMonoBorderedBuilder.h"

// Global variable declarations
const  ConnectorLocalInfo applicationInfo = { "PicoSDK Oled", "3acc6301-dadd-4730-b142-9541180d2aa8" };
TcMenuRemoteServer remoteServer(applicationInfo);

AdafruitSSD1306Spi* gfx;
AdafruitDrawable gfxDrawable;
GraphicsDeviceRenderer renderer(30, applicationInfo.name, nullptr);
NoInitialisationNeeded stdioInitializer;
StdioTransport stdioTransport(255);
TagValueRemoteServerConnection stdioConnection(stdioTransport, stdioInitializer);

void setupMenu() {
    // First we set up eeprom and authentication (if needed).
    setEepromStorageMode(TC_STORE_ROM_DYNAMIC);
    TcMenuBuilder builder = TcMenuBuilder(&MenuManager::ROOT);
    buildMenu(builder);

    // Code generated by plugins and new operators.
        gfx = new AdafruitSSD1306Spi(SPIWithSettings(spi_default, 15, 10000000), 14, 13, 64, 128, ENCMODE_UTF8, SSD_1306);
        gfx->setRotation(0);
        gfx->begin();
        renderer.setUpdatesPerSecond(10);
        gfxDrawable.setGraphics(gfx);
        gfxDrawable.setFontHandler(gfx->getFontHandler());
        renderer.setDrawable(&gfxDrawable);
        StateRotaryEncoderBuilder encBuild;
        encBuild.withEncoderPins(17, 16)
           .interruptOnBothPins()
           .withCallback([](const int value) {menuMgr.valueChanged(value); })
           .withEncoderType(FULL_CYCLE)
           .build();
        switches.onRelease(21, [](pinid_t /*key*/, const bool held) { menuMgr.onMenuSelect(held); });
        menuMgr.initWithoutInput(&renderer, &getMenuVolume());
        remoteServer.addConnection(&stdioConnection);
        applyTheme(renderer);
}

