/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

// PLUGIN FILE - tcMenuAdaFruitGfxMono.h
/*
 * Copyright (c) 2018 https://www.thecoderscorner.com (Dave Cherry).
 * This product is licensed under an Apache license, see the LICENSE file in the top-level directory.
 */

/**
 * @file tcMenuAdaFruitGfx.h
 *
 * AdaFruit_GFX renderer that renders menus onto this type of display. This file is a plugin file and should not
 * be directly edited, it will be replaced each time the project is built. If you want to edit this file in place,
 * make sure to rename it first.
 *
 * LIBRARY REQUIREMENT
 * This library requires the AdaGfx library along with a suitable driver.
 */


#ifndef _TCMENU_TCMENUADAFRUITGFX_H_
#define _TCMENU_TCMENUADAFRUITGFX_H_

#include <tcMenu.h>
#include <tcUtil.h>
#include <BaseRenderers.h>
#include <tcUnicodeHelper.h>
#include <Adafruit_GFX.h>
#include <oled/AdafruitSSD1306Spi.h>
#include <graphics/GfxMenuConfig.h>
#include <BaseDialog.h>
#include <graphics/BaseGraphicalRenderer.h>
#include <graphics/GraphicsDeviceRenderer.h>
#include <AnalogDeviceAbstraction.h>

using namespace tcgfx;

// some colour displays don't create this value
#ifndef BLACK
#define BLACK 0
#endif

// some colour displays don't create this value
#ifndef WHITE
#define WHITE 0xffff
#endif

extern const ConnectorLocalInfo applicationInfo;

/**
   @brief      Draw a RAM-resident 1-bit image at the specified (x,y) position,
   from image data that may be wider or taller than the desired width and height.
   Imagine a cookie dough rolled out, where you can cut a rectangle out of it.
   It uses the specified foreground (for set bits) and background (unset bits) colors.
   This is particularly useful for GFXCanvas1 operations, where you can allocate the
   largest canvas needed and then use it for all drawing operations.

    @param    gfx The actual graphics object to draw onto
    @param    x   Top left corner x coordinate
    @param    y   Top left corner y coordinate
    @param    bitmap  byte array with monochrome bitmap
    @param    w   width of the portion you want to draw
    @param    h   Height of the portion you want to draw
    @param    totalWidth actual width of the bitmap
    @param    xStart X position of the image in the data
    @param    yStart Y position of the image in the data
    @param    fgColor 16-bit 5-6-5 Color to draw pixels with
    @param    bgColor 16-bit 5-6-5 Color to draw background with
*/
void drawCookieCutBitmap(Adafruit_GFX* gfx, int16_t x, int16_t y, const uint8_t *bitmap, int16_t w,
                         int16_t h, int16_t totalWidth, int16_t xStart, int16_t yStart,
                         uint16_t fgColor, uint16_t bgColor);

/**
 * A standard menu render configuration that describes how to renderer each item and the title.
 * Specialised for Adafruit_GFX fonts.
 */
typedef struct ColorGfxMenuConfig<const GFXfont*> AdaColorGfxMenuConfig;

/**
 * A basic renderer that can use the AdaFruit_GFX library to render information onto a suitable
 * display. It is your responsibility to fully initialise and prepare the display before passing
 * it to this renderer. The usual procedure is to create a display variable globally in your
 * sketch and then provide that as the parameter to setGraphicsDevice. If you are using the
 * designer you provide the display variable name in the code generation parameters.
 *
 * You can also override many elements of the display using AdaColorGfxMenuConfig, to use the defaults
 * just call prepareAdaColorDefaultGfxConfig(..) passing it a pointer to your config object. Again the
 * designer UI takes care of this.
 */
class AdafruitDrawable : public DeviceDrawable {
private:
    Adafruit_GFX* graphics;
    const GFXfont* computedFont = nullptr;
    int16_t computedBaseline = 0;
    int16_t computedHeight = 0;
public:
    explicit AdafruitDrawable() : graphics(nullptr) {}
    explicit AdafruitDrawable(Adafruit_GFX* graphics, int spriteHeight = 0) : graphics(graphics) {
        setSubDeviceType(NO_SUB_DEVICE);
    }
    ~AdafruitDrawable() override = default;

    Coord getDisplayDimensions() override {
        return Coord(graphics->width(), graphics->height());
    }

    DeviceDrawable *getSubDeviceFor(const Coord& w, const Coord& s, const color_t *pal, int palSize) override { return nullptr; }
    void transaction(bool isStarting, bool redrawNeeded) override;
    void internalDrawText(const Coord &where, const void *font, int mag, const char *text) override;
    void drawBitmap(const Coord &where, const DrawableIcon *icon, bool selected) override;
    void drawXBitmap(const Coord &where, const Coord &size, const uint8_t *data) override;
    void drawBox(const Coord &where, const Coord &size, bool filled) override;
    void drawCircle(const Coord& where, int radius, bool filled) override;
    void drawPolygon(const Coord points[], int numPoints, bool filled) override;
    Coord internalTextExtents(const void *font, int mag, const char *text, int *baseline) override;
    void drawPixel(uint16_t x, uint16_t y) override;
    Adafruit_GFX* getGfx() { return graphics; }
    void setGraphics(Adafruit_GFX* gfx) { graphics = gfx; }
protected:
    void computeBaselineIfNeeded(const GFXfont* font);
    UnicodeFontHandler *createFontHandler() override;
};

#endif /* _TCMENU_TCMENUADAFRUITGFX_H_ */


// PLUGIN FILE - StdioTransport.h
#ifndef STDIO_TRANSPORT_H
#define STDIO_TRANSPORT_H

#include <PlatformDetermination.h>
#include <RemoteConnector.h>
#include <remote/BaseRemoteComponents.h>
#include "SCCircularBuffer.h"

namespace tcremote {

    class StdioTransport : public TagValueTransport {
    private:
        SCCircularBuffer inputBuffer;
    public:
        explicit StdioTransport(int readBufferSize) : inputBuffer(readBufferSize), TagValueTransport(TVAL_UNBUFFERED) {}

        void flush() override { stdio_flush(); }

        int writeChar(char data) override;

        int writeStr(const char *data) override;

        uint8_t readByte() override;

        bool readAvailable() override;

        bool available() override { return true; }

        bool connected() override { return true; }

        void close() override;
    };
}

#ifndef TC_MANUAL_NAMESPACING
using namespace tcremote;
#endif // TC_MANUAL_NAMESPACING

#endif //STDIO_TRANSPORT_H

#include <PlatformDetermination.h>
#include <tcMenu.h>


#include <tcMenuBuilder.h>
#include "Adafruit_SSD1306.h"
#include <StateMachineEncoder.h>
#include <RemoteConnector.h>
#include <tcUnicodeHelper.h>
#include <ScrollChoiceMenuItem.h>
#include <RemoteMenuItem.h>
#include <IoAbstraction.h>
#include <EepromItemStorage.h>

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern TcMenuRemoteServer remoteServer;
extern AdafruitSSD1306Spi* gfx;
extern AdafruitDrawable gfxDrawable;
extern GraphicsDeviceRenderer renderer;
extern const UnicodeFont OpenSansRegular7pt[];
extern const UnicodeFont OpenSansRegular8pt[];

// Any externals needed by IO expanders, EEPROMs etc


// Forward define the menu builder function
void buildMenu(TcMenuBuilder& builder);

// The following defines all menu item IDs.
#define MENU_VOLUME_ID  1
#define MENU_CHANNEL_ID  2
#define MENU_MUTE_ID  3
#define MENU_DIRECT_ID  4
#define MENU_STATUS_ID  5
#define MENU_LEFT_VU_ID  6
#define MENU_RIGHT_VU_ID  7
#define MENU_STATE_ID  8
#define MENU_A0_LEVEL_ID  9
#define MENU_RUNTIMES_ID  10
#define MENU_TIME24_ID  11
#define MENU_TIME12_ID  12
#define MENU_DATE_GR_ID  13
#define MENU_SHOW_DIALOG_ID  14
#define MENU_DIALOG_ACTIVE_ID  15
#define MENU_DYNAMIC_ID  16
#define MENU_ENABLE_ID  17
#define MENU_SET1_A_ID  18
#define MENU_SET1_B_ID  19
#define MENU_SET1_C_ID  20
#define MENU_SET1_D_ID  21
#define MENU_SET2_A_ID  22
#define MENU_SET2_B_ID  23
#define MENU_LIST_CUSTOM_ID  24
#define MENU_FLASH_LIST_ID  25

// Inline helper methods to access menu items
inline AnalogMenuItem& getMenuVolume() { return getAnalogItemById(MENU_VOLUME_ID); }
inline EnumMenuItem& getMenuChannel() { return getEnumItemById(MENU_CHANNEL_ID); }
inline BooleanMenuItem& getMenuMute() { return getBooleanItemById(MENU_MUTE_ID); }
inline BooleanMenuItem& getMenuDirect() { return getBooleanItemById(MENU_DIRECT_ID); }
inline SubMenuItem& getMenuStatus() { return getSubMenuById(MENU_STATUS_ID); }
inline AnalogMenuItem& getMenuLeftVU() { return getAnalogItemById(MENU_LEFT_VU_ID); }
inline AnalogMenuItem& getMenuRightVU() { return getAnalogItemById(MENU_RIGHT_VU_ID); }
inline EnumMenuItem& getMenuState() { return getEnumItemById(MENU_STATE_ID); }
inline FloatMenuItem& getMenuA0Level() { return getFloatItemById(MENU_A0_LEVEL_ID); }
inline SubMenuItem& getMenuRuntimes() { return getSubMenuById(MENU_RUNTIMES_ID); }
inline TimeFormattedMenuItem& getMenuTime24() { return getTimeItemById(MENU_TIME24_ID); }
inline TimeFormattedMenuItem& getMenuTime12() { return getTimeItemById(MENU_TIME12_ID); }
inline DateFormattedMenuItem& getMenuDateGr() { return getDateItemById(MENU_DATE_GR_ID); }
inline ActionMenuItem& getMenuShowDialog() { return getActionItemById(MENU_SHOW_DIALOG_ID); }
inline EnumMenuItem& getMenuDialogActive() { return getEnumItemById(MENU_DIALOG_ACTIVE_ID); }
inline SubMenuItem& getMenuDynamic() { return getSubMenuById(MENU_DYNAMIC_ID); }
inline EnumMenuItem& getMenuEnable() { return getEnumItemById(MENU_ENABLE_ID); }
inline AnalogMenuItem& getMenuSet1A() { return getAnalogItemById(MENU_SET1_A_ID); }
inline FloatMenuItem& getMenuSet1B() { return getFloatItemById(MENU_SET1_B_ID); }
inline BooleanMenuItem& getMenuSet1C() { return getBooleanItemById(MENU_SET1_C_ID); }
inline Rgb32MenuItem& getMenuSet1D() { return getRgb32ItemById(MENU_SET1_D_ID); }
inline ActionMenuItem& getMenuSet2A() { return getActionItemById(MENU_SET2_A_ID); }
inline BooleanMenuItem& getMenuSet2B() { return getBooleanItemById(MENU_SET2_B_ID); }
inline ListRuntimeMenuItem& getMenuListCustom() { return getListItemById(MENU_LIST_CUSTOM_ID); }
inline ListRuntimeMenuItem& getMenuFlashList() { return getListItemById(MENU_FLASH_LIST_ID); }


// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return getMenuVolume(); }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION StatusAppeared(int id);
int fnListCustomRtCall(RuntimeMenuItem* item, uint8_t row, RenderFnMode mode, char* buffer, int bufferSize);
void CALLBACK_FUNCTION onEnableChange(int id);
void CALLBACK_FUNCTION onShowDialog(int id);
void CALLBACK_FUNCTION onVolumeChanged(int id);

#endif // MENU_GENERATED_CODE_H
