/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <tcMenu.h>

#include <LiquidCrystalIO.h>
#include <IoAbstractionWire.h>
#include <JoystickSwitchInput.h>
#include <RuntimeMenuItem.h>
#include "tcMenuLiquidCrystal.h"

// all define statements needed
#define LCD_WIDTH 20
#define LCD_HEIGHT 4
#define I2C_ADDRESS 0x40
#define PIN_LAYOUT RS_RW_EN
#define PULLUP_LOGIC true
#define INTERRUPT_SWITCHES false
#define SWITCH_IODEVICE io23017
#define JOYSTICK_PIN A0
#define BUTTON_PIN A1

// all variables that need exporting
extern LiquidCrystal lcd;
extern LiquidCrystalRenderer renderer;
extern MBedAnalogDevice analogDevice;

// all menu item forward references.
extern IpAddressMenuItem menuConnectivityIPAddress;
extern TextMenuItem menuConnectivityChangePin;
extern BackMenuItem menuBackConnectivity;
extern SubMenuItem menuConnectivity;
extern ActionMenuItem menuSettingsSaveSettings;
extern AnalogMenuItem menuSettingsPower;
extern BooleanMenuItem menuSettingsEnabled;
extern BackMenuItem menuBackSettings;
extern SubMenuItem menuSettings;
extern ActionMenuItem menuQuestionDialog;
extern ActionMenuItem menuInfoDialog;
extern TextMenuItem menuText;
extern EnumMenuItem menuFood;
extern ActionMenuItem menuTakeDisplay;
extern TimeFormattedMenuItem menuTime;
extern const ConnectorLocalInfo applicationInfo;

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION onChangePin(int id);
void CALLBACK_FUNCTION onFoodChoice(int id);
void CALLBACK_FUNCTION onInfoDlg(int id);
void CALLBACK_FUNCTION onQuestionDlg(int id);
void CALLBACK_FUNCTION onSaveSettings(int id);
void CALLBACK_FUNCTION onTakeOverDisplay(int id);

void setupMenu();

#endif // MENU_GENERATED_CODE_H
