/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#include <tcMenu.h>
#include "mbedMenuJava_menu.h"

// Global variable declarations

LiquidCrystal lcd(0, 1, 2, 4, 5, 6, 7);
LiquidCrystalRenderer renderer(lcd, 20, 4);

// Global Menu Item declarations

const char enumStrSubMenuFoods_0[] = "Pizza";
const char enumStrSubMenuFoods_1[] = "Pasta";
const char enumStrSubMenuFoods_2[] = "Salad";
const char enumStrSubMenuFoods_3[] = "Beef";
const char enumStrSubMenuFoods_4[] = "Falafel";
const char* const enumStrSubMenuFoods[]  = { enumStrSubMenuFoods_0, enumStrSubMenuFoods_1, enumStrSubMenuFoods_2, enumStrSubMenuFoods_3, enumStrSubMenuFoods_4 };
const EnumMenuInfo minfoSubMenuFoods = { "Foods", 10, 0xffff, 4, NO_CALLBACK, enumStrSubMenuFoods };
EnumMenuItem menuSubMenuFoods(&minfoSubMenuFoods, 0, NULL);
RENDERING_CALLBACK_NAME_INVOKE(fnSubMenuEditIPRtCall, ipAddressRenderFn, "Edit IP", -1, NULL)
IpAddressMenuItem menuSubMenuEditIP(fnSubMenuEditIPRtCall, 9, &menuSubMenuFoods);
RENDERING_CALLBACK_NAME_INVOKE(fnSubMenuIPAddressRtCall, ipAddressRenderFn, "IP Address", -1, NULL)
IpAddressMenuItem menuSubMenuIPAddress(fnSubMenuIPAddressRtCall, 8, &menuSubMenuEditIP);
RENDERING_CALLBACK_NAME_INVOKE(fnSubMenuLargeNumRtCall, largeNumItemRenderFn, "Large Num", -1, NULL)
EditableLargeNumberMenuItem menuSubMenuLargeNum(fnSubMenuLargeNumRtCall, 7, 7, 3, &menuSubMenuIPAddress);
RENDERING_CALLBACK_NAME_INVOKE(fnSubMenuRtCall, backSubItemRenderFn, "Sub Menu", -1, NULL)
const SubMenuInfo minfoSubMenu = { "Sub Menu", 6, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackSubMenu(fnSubMenuRtCall, &menuSubMenuLargeNum);
SubMenuItem menuSubMenu(&minfoSubMenu, &menuBackSubMenu, NULL);
const FloatMenuInfo minfoA0Value = { "A0 Value", 5, 0xffff, 3, NO_CALLBACK };
FloatMenuItem menuA0Value(&minfoA0Value, &menuSubMenu);
const BooleanMenuInfo minfoABoolean = { "A Boolean", 4, 0xffff, 1, onUserButton, NAMING_TRUE_FALSE };
BooleanMenuItem menuABoolean(&minfoABoolean, false, &menuA0Value);
const AnalogMenuInfo minfoAnalogValue = { "Analog Value", 2, 0xffff, 100, NO_CALLBACK, 0, 0, "" };
AnalogMenuItem menuAnalogValue(&minfoAnalogValue, 0, &menuABoolean);
RENDERING_CALLBACK_NAME_INVOKE(fnRTCDateRtCall, dateItemRenderFn, "RTC Date", -1, NULL)
DateFormattedMenuItem menuRTCDate(fnRTCDateRtCall, 3, &menuAnalogValue);
RENDERING_CALLBACK_NAME_INVOKE(fnRTCTimeRtCall, timeItemRenderFn, "RTC Time", -1, NULL)
TimeFormattedMenuItem menuRTCTime(fnRTCTimeRtCall, 1, (MultiEditWireType)3, &menuRTCDate);
const ConnectorLocalInfo applicationInfo = { "MBed Test", "98ea360b-fe08-444a-996b-2e94dda7a2eb" };

// Set up code

void setupMenu() {
    lcd.setIoAbstraction(ioFrom8574(0x40, 0xff, &i2c));
    lcd.begin(20, 4);
    lcd.configureBacklightPin(3);
    lcd.backlight();
    switches.initialise(internalDigitalIo(), true);
    menuMgr.initForEncoder(&renderer, &menuRTCTime, PA_6, PD_14, PA_5);
    remoteServer.begin(3333, &applicationInfo);

    // Read only and local only function calls
    menuSubMenuIPAddress.setReadOnly(true);
    menuRTCDate.setReadOnly(true);
    menuRTCTime.setReadOnly(true);
}

