/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>
#include "tcMenuAdaFruitGfx.h"
#include <RuntimeMenuItem.h>
#include <IoAbstraction.h>

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern Adafruit_ST7735 gfx;
extern AdafruitDrawable gfxDrawable;
extern GraphicsDeviceRenderer renderer;
extern const GFXfont FreeSans9pt7b;

// Any externals needed by IO expanders, EEPROMs etc


// Global Menu Item exports
extern ActionMenuItem menuEmergencyAlarm;
extern AnalogMenuItem menuTemperature;
extern TextMenuItem menuZones;
extern EnumMenuItem menuStatus;
extern ListRuntimeMenuItem menuZoneHistory;
extern BooleanMenuItem menuZonesEnableFire;
extern BooleanMenuItem menuZonesEnableZ3;
extern BooleanMenuItem menuZonesEnableZ2;
extern BooleanMenuItem menuZonesEnableZ1;
extern BackMenuItem menuBackZone;
extern SubMenuItem menuZone;
extern BooleanMenuItem menuArmed;

// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return menuArmed; }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

int fnZoneHistoryRtCall(RuntimeMenuItem* item, uint8_t row, RenderFnMode mode, char* buffer, int bufferSize);
void CALLBACK_FUNCTION onArmed(int id);
void CALLBACK_FUNCTION onZoneEnablement(int id);

#endif // MENU_GENERATED_CODE_H
